services:
  out-nginx:
    image: nginx:stable
    volumes:
      - ./out-nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /dev/shm/:/dev/shm/
      - /watorvapor/ecdsa-cert/certbot/etc:/etc/cert
      - /watorvapor/log/nginx:/log
    network_mode : 'host'
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 64M
  11ty-nginx:
    image: nginx:stable
    volumes:
      - ./11ty-static/site_dist:/www
      - ../otmc-package:/www/assets/js
      - ./11ty-static/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /dev/shm/:/dev/shm/
    network_mode : 'none'
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 64M
  11ty-ssg:
    image: node:lts
    network_mode: 'none'
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./11ty-static:/11ty
      - /dev/shm/:/dev/shm/
    working_dir: '/11ty'
    command: node ./index.mjs
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
