version: '3'
services:
  nginx:
    image: nginx:stable
    volumes:
      - ./www:/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /dev/shm/:/dev/shm/
    network_mode : 'host'
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 64M
