services:
  rtk-bs:
    image: node:24
    privileged: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ../otmc-hub:/otmc/otmc-hub
      - ../otmc-package:/otmc/otmc-package
      - /opt/otmc/:/opt/otmc/
      - /dev/shm/:/dev/shm/
    working_dir: '/otmc/otmc-hub/rtk-gnss-station'
    command: node ./index.mjs
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
