services:
  redis:
    image: redis:8.0
    network_mode : 'none'
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /opt/otmc/store1/redis:/var/run
      - /dev/shm:/dev/shm
    command: redis-server /usr/local/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 64M
  gateway:
    image: node:22
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ../otmc-hub:/otmc/otmc-hub
      - ../otmc-package:/otmc/otmc-package
      - /opt/otmc/:/opt/otmc/
      - /dev/shm/:/dev/shm/
    working_dir: '/otmc/otmc-hub/core.gateway'
    command: node ./index.mjs
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
