name: OTMC
on: [push]
jobs:
  Test:
    name: Run test codes
    runs-on: [self-hosted]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Show files
      run: pwd;find ./
    - name: Jest prepare
      run: cd otmc-package/test && npm install
    - name: Run jest
      run: cd otmc-package/test && npm run test
