name: OTMC
on: [push]
jobs:
  Test:
    name: Run test codes
    runs-on: [self-hosted]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Show files
      run: pwd;find ./
    - name: Install and cache nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 23.x
        node-version-file: otmc-package/test/package.json
    - name: Install packages
      run: cd otmc-package/test && npm install
    - name: Run jest
      run: cd otmc-package/test && node --test
